#!/usr/bin/env bash
JOB_PWD=/home/oracle/projects/massive_elb_logs_archive_production/data/raw/ott_dazn/docomo_investigations/logs-archive-production/data_loading
#JOB_PWD=$(pwd)
YES_DAT=$(date --date=' 1 days ago' '+%y%d%m')
mkdir -p $JOB_PWD/list_files
rm $JOB_PWD/list_files/yesterday.txt
touch $JOB_PWD/list_files/yesterday.txt
echo "$YES_DAT" >> $JOB_PWD/list_files/yesterday.txt
cat  $JOB_PWD/list_files/yesterday.txt
bash -x $JOB_PWD/execute_list_script.sh $JOB_PWD/list_file/yesterday.txt $JOB_PWD/load_rawjson-ixpbda08
echo 1
