#!/usr/bin/env bash
DATE_V1=$1
if [ -z "$DATE_V1" ]
then
 DATE_V1=20170101
fi

if [ -z "$PATH_JOB_DIR" ]; then
    PATH_JOB_DIR=/home/oracle/projects/massive_elb_logs_archive_production/data/raw/ott_dazn/docomo_investigations/logs-archive-production/data_loading
fi

echo "LOAD RAW DATA FOR DATE_20=${DATE_V1}"
hdfs dfs -mkdir -p /data/raw/ott_dazn/docomo_investigations/logs-archive-production/gzip/dt=20${DATE_V1}
hdfs dfs -moveFromLocal ${PATH_JOB_DIR}/${DATE_V1}/* /data/raw/ott_dazn/docomo_investigations/logs-archive-production/gzip/dt=20${DATE_V1}
hdfs dfs -ls /data/raw/ott_dazn/docomo_investigations/logs-archive-production/gzip/dt=20${DATE_V1}
# hdfs dfs -mkdir -p /data/staged/ott_dazn/docomo_investigations/logs-archive-production/parquet
# echo "STAGE RAW DATA AS PARQUET FOR DATE 20${DATE_V1} with SPARK"

echo 1
