#!/usr/bin/env bash

DATE_V1=$1
if [ -z "$DATE_V1" ]
then
 DATE_V1=20180214
fi

if [ -f ~/.keytabs/$(whoami).keytab ]; then
  # for any:any credentials
  export KRB5CCNAME=/tmp/krb5cc_$(id -u)

  kinit -kt ~/.keytabs/$(whoami).keytab $(whoami)/chpbda@BDA2.PERFORMGROUP.COM -c /tmp/krb5cc_$(id -u)
  klist /tmp/krb5cc_$(id -u)
else
  echo "No Kerberos here"
fi

echo "RAW d=${DATE_V1} FILES COUNT : "
hdfs dfs -ls /data/raw/ott_dazn/logs-archive-production/dt=${DATE_V1}/*.gz | wc -l

hdfs dfs -mkdir -p /data/staged/ott_dazn/logs-archive-production/parquet

echo "Clean Stage to Avoid Duplicates of dt=${DATE_V1}"
hdfs dfs -rm -r -f -skipTrash  /data/staged/ott_dazn/logs-archive-production/parquet/dt=${DATE_V1}/*.parquet 

echo "TOTAL STAGED FILES COUNT : "
hdfs dfs -ls -R /data/staged/ott_dazn/logs-archive-production/parquet/dt=*/*.parquet | wc -l

echo "STAGE RAW DATA AS PARQUET FOR DATE ${DATE_V1} with SPARK"

# Spark Job Operations
MAIN_CLASS1=ptv.content.akamailogs.staged.parquetindexer.SparkStageLogsArchiveProdWorkArround
APP_JAR=/home/siemanalyst/projects/logs-archive-production/data_etl/parquetindexer-1.0-TPOC-jar-with-dependencies.jar
EXTRA_JAR=/home/siemanalyst/projects/logs-archive-production/data_etl/parquetindexer-1.0-TPOC-jar-with-dependencies.jar

# Additional for Spark container 

MASTER_URL=yarn
DEPLOY_MODE=client

DRIVER_MEMORY=17G
DRIVER_CORES=4
EXECUTOR_MEMORY=11G
EXECUTOR_CORES=2
NUM_EXECUTORS=48

# Introduction of Coalesce Factor - Covers Size Growth
#COALESCEFACTOR=72
#COALESCEFACTOR=144
COALESCEFACTOR=288
#COALESCEFACTOR=576

# Additional Logic workarround for new null token DI
#
IN_PATH="/data/raw/ott_dazn/logs-archive-production/"
OUT_PATH="/data/staged/ott_dazn/logs-archive-production/parquet/"
#

spark2-submit  --class ${MAIN_CLASS1} --master ${MASTER_URL} --deploy-mode ${DEPLOY_MODE}  \
  --principal $(whoami)/chpbda@BDA2.PERFORMGROUP.COM --keytab ~/.keytabs/$(whoami).keytab \
  --conf "spark.debug.maxToStringFields=1500" --conf "spark.dynamicAllocation.enabled=false" \
  --driver-memory ${DRIVER_MEMORY} --driver-cores ${DRIVER_CORES} \
  --num-executors ${NUM_EXECUTORS} --executor-memory ${EXECUTOR_MEMORY} --executor-cores ${EXECUTOR_CORES}  \
  --jars ${APP_JAR} ${EXTRA_JAR} --processdate ${DATE_V1} --inputpath ${IN_PATH} --outputpath ${OUT_PATH} --coalescefactor ${COALESCEFACTOR}  >> /home/siemanalyst/projects/logs-archive-production/data_etl/logs/SparkStageLogsArchiveProd-1-${DATE_V1}.log
#

echo 1
